apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-weather-app
  labels:
    app: react-weather-app
spec:
  selector:
    matchLabels:
      app: react-weather-app
  replicas: 1
  template:
    metadata:
      name: react-weather-app
      labels:
        app: react-weather-app
    spec:
      imagePullSecrets:
      - name: dockerhub      
      containers:
        - name: react-weather-app
          image: docker.io/hiondal/react-weather-app:latest
          imagePullPolicy: Always
          ports:
            - name: port1
              containerPort: 8081
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi

---

apiVersion: v1
kind: Service
metadata:
  name: react-weather-app
spec:
  type: ClusterIP
  selector:
    app: react-weather-app
  ports:
    - name: react-weather-app
      port: 8080
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-weather-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: react-weather-app-hiondal.165.192.105.60.nip.io
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: react-weather-app
                port: 
                  number: 8080
