FROM nginx:latest

COPY ./build /usr/share/nginx/html

## Copy web configuration 
COPY ./deployment/default.conf.template /etc/nginx/conf.d/default.conf
#
## 80포트 오픈하고 nginx 실행
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
